//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TE_Demo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TE_DEMO_DIALOG              102
#define IDD_PROPPAGE_LARGE              107
#define IDR_MAINFRAME                   128
#define IDD_COMMINGCALL_DIALOG          130
#define IDD_DIALOG_PREVIEW              135
#define IDD_DLG_DESK_RIM                137
#define IDD_DIALOG1                     138
#define IDD_OUTSIDE_DLG                 138
#define IDB_BITMAP_CONF                 142
#define IDD_DIALOG_CONF                 144
#define IDB_BITMAP_TIME                 145
#define IDB_BITMAP_CHAIRMAN             149
#define IDB_BITMAP2                     150
#define IDB_BITMAP_ADD                  150
#define IDB_BITMAP_MUTI                 151
#define IDB_BITMAP_UNMUTE               152
#define IDB_BITMAP_MUTE                 153
#define IDB_BITMAP_OUT                  155
#define IDB_BITMAP_BROADCAST            156
#define IDD_DIALOG_APPLY_CHAIRMAN       157
#define IDB_BITMAP_CHAIRMAN1            159
#define IDD_DIALOG_INVITETOJION         159
#define IDD_DIALOG_EXTEND_TIME          160
#define IDR_MENU_POPUP                  161
#define IDD_DIALOG_AN                   163
#define IDD_DIALOG_ANSWER_REJECT        163
#define IDD_DIALOG2                     164
#define IDD_DIALOG_CONTACT              165
#define IDD_DIALOG_CONTACTINFO          166
#define IDR_MENU_CONTACT                167
#define IDD_DIALOG_GROUP                168
#define IDD_DIALOG_RenameGroup          169
#define IDD_DIALOG_NICKNAME             170
#define IDD_DIALOG_IMPORT               171
#define IDD_DIALOG_IMPORTFILE           172
#define IDD_DIALOG_EXPORTGROUP          173
#define IDD_DIALOG_CONFERENCE_CONTACTS  174
#define IDB_BITMAP_DIAL_PLATE           178
#define IDD_DIALOG3                     179
#define IDD_DIALOG_DIAL                 180
#define IDD_DIALOG_ENTERPRISE_ADDR      181
#define IDD_DIALOG_HISTORYRECORD        182
#define IDR_MENU_HISTORY                183
#define IDC_EDIT1                       1000
#define IDC_PORT_NUM                    1001
#define IDC_USERNAME                    1002
#define IDC_PASSWORD                    1003
#define IDC_CALL_BUTTON                 1005
#define IDLOGIN                         1006
#define IDC_SERVER_IP                   1007
#define IDC_CALLNUM                     1009
#define IDC_HANGUP_BUTTON               1010
#define IDC_SPEAKER_BUTTON              1012
#define IDC_MIC_BUTTON                  1013
#define IDC_SPEAKER_BUTTON2             1014
#define IDC_BUTTON2                     1015
#define IDC_MIC_BUTTON2                 1015
#define IDC_BTN_APPLY_CHAIRMAN          1015
#define IDC_BUTTON1                     1016
#define IDC_VIDEO_BUTTON                1016
#define IDC_BUTTON_VIDEOPREVIEW         1016
#define IDC_BTN_EXTEND_TIME             1016
#define IDC_BUTTON_APPLY                1016
#define IDC_BTN_INVITE                  1016
#define IDC_CALL_STATE                  1017
#define IDANSWER                        1018
#define IDREJECT                        1019
#define IDC_STATIC_REMOTE               1020
#define IDC_STATIC_LOCAL                1021
#define IDC_CHECK2                      1023
#define IDC_IPADDRESS2                  1025
#define IDC_SERVER_IPADDRESS            1025
#define IDLOGOUT                        1026
#define IDC_STATIC_PREVIEW              1030
#define IDC_STARTSHARE_BTN              1031
#define IDC_STOPSHARE_BTN               1032
#define IDC_STATIC_DISPLAYSHARE         1033
#define IDC_SHAREEXE_BTN                1034
#define IDC_LIST_APPS                   1035
#define IDC_COMBO1                      1036
#define IDC_STATIC1                     1037
#define IDC_BUTTON_CONF                 1038
#define IDC_BUTTON_CONFCREATE           1039
#define IDC_STATIC_INFO                 1041
#define IDC_BTN_ADD_MEM                 1042
#define IDC_LIST_JIONED_MEM             1044
#define IDC_EDIT_PASSWORD               1046
#define IDC_STATIC2                     1047
#define IDC_STATIC3                     1048
#define IDC_BTN_RELEASE_CHAIRMAN        1049
#define IDC_LIST_MEMBERS                1051
#define IDC_STATIC_INVITE_NOTE          1053
#define IDC_COMBO_TIME                  1054
#define IDC_BTN_ATOV                    1055
#define IDC_BTN_VTOA                    1056
#define IDC_EDIT_NAME                   1058
#define IDC_CHECK1                      1058
#define IDC_EDIT2                       1059
#define IDC_TREE1                       1059
#define IDC_EDIT3                       1060
#define IDC_EDIT4                       1061
#define IDC_EDIT5                       1062
#define IDC_EDIT6                       1063
#define IDC_COMBO_GROUP                 1064
#define IDC_BUTTON3                     1065
#define IDC_BUTTON4                     1066
#define IDC_BUTTON6                     1067
#define IDC_LIST1                       1067
#define IDC_EDIT7                       1068
#define IDC_BUTTON_SWITCH_CAMERA        1069
#define IDC_BTN_DIAL_PLATE              1070
#define IDC_BUTTON5                     1071
#define IDC_BUTTON7                     1072
#define IDC_BUTTON8                     1073
#define IDC_BUTTON9                     1074
#define IDC_BUTTON10                    1075
#define IDC_BUTTON11                    1076
#define IDC_BUTTON12                    1077
#define IDC_COMBO2                      1078
#define IDC_SLIDER_VOICEOUT             1079
#define IDC_SLIDER_VOICEIN              1080
#define IDC_BTN_VEDIOANSWER             1081
#define IDC_COMBO3                      1082
#define IDC_COMBO4                      1083
#define IDC_EDIT_SEARCH_ADDR            1085
#define IDC_EDIT_HISTORY_SEARCH         1086
#define IDC_BUTTON_HISTORY_SEARCH       1087
#define IDC_BUTTON_SEARCH               1088
#define IDC_EDIT_SEARCH                 1089
#define IDC_IPADDRESS1                  1090
#define IDC_LICENSE_IPADDRESS           1090
#define ID_Menu                         32771
#define ID_MENU_MUTE                    32772
#define ID                              32773
#define ID_MENU_UNMUTE                  32774
#define ID_MENU_APPLY                   32775
#define ID_MENU_RELEASE                 32776
#define ID_MENU_BROADCAST               32777
#define ID_Menu32778                    32778
#define ID_MENU_STOP_BROADCAST          32779
#define ID_MENU_CALLUP                  32780
#define ID_MENU_DELETE                  32781
#define ID_MENU_HANDUP                  32782
#define ID_MENU_WATCH                   32783
#define ID_32785                        32785
#define ID_32786                        32786
#define ID_FDS_DS                       32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
